import type { NewSchedule } from '../types/schedule'

/**
 * 앱을 처음 사용하는 사용자를 위한 예제 스케줄 데이터
 */
export const EXAMPLE_SCHEDULES: NewSchedule[] = [
  {
    date: '2020.12.25',
    time: '14:00',
    location: '라움 웨딩홀 (서울 강남구)',
    couple: '김코딩 박디자인',
    cuts: 2800,
    price: 1500000,
    contact: '010-1234-5678',
    memo: '크리스마스 웨딩 🎄 신랑님 개발자, 신부님 디자이너 커플! 테크 감성 원해요',
    brand: 'K7',
    album: '프리미엄',
    photographer: '김사진',
    manager: '이매니저',
    isDuplicate: false,
  },
  {
    date: '2020.11.15',
    time: '11:30',
    location: '더 파티움 (서울 성동구)',
    couple: '최프론트 정백엔드',
    cuts: 3600,
    price: 1200000,
    contact: '010-9876-5432',
    memo: '풀스택 커플의 만남! 야외 정원 촬영 필수 📸 React ♥ FastAPI',
    brand: 'B7',
    album: '스탠다드',
    photographer: '박셔터',
    manager: '김코디',
    isDuplicate: false,
  },
  {
    date: '2020.10.20',
    time: '16:00',
    location: '엘비스 웨딩홀 (경기 성남시)',
    couple: '이아이유 박서준',
    cuts: 7560,
    price: 2500000,
    contact: '010-5555-7777',
    memo: '☆ VIP 패키지 ☆ 유명인 촬영이라 조용히! 비공개 사진만 SNS 가능',
    brand: 'A+',
    album: 'VIP',
    photographer: '최프로',
    manager: '윤매니저',
    isDuplicate: false,
  },
  {
    date: '2020.09.09',
    time: '13:00',
    location: '마리아주 웨딩홀 (인천 송도)',
    couple: '한개발 송기획',
    cuts: 2700,
    price: 1800000,
    contact: '010-3333-9999',
    memo: '9월 9일 구구데이 💑 IT 기업 만난 커플, 드론 촬영 추가 요청!',
    brand: 'Graphy',
    album: '프리미엄',
    photographer: '정작가',
    manager: '최플래너',
    isDuplicate: false,
  },
]
